#!/bin/bash

# setup_yazi_portal.sh
# Automates the setup of Yazi as the file chooser using xdg-desktop-portal-termfilechooser
# Designed for Arch Linux / Hyprland / Ghostty users.

set -e

echo "--- Starting Yazi Portal Setup ---"

# 1. Check for required tools
if ! command -v yazi &> /dev/null; then
    echo "Error: 'yazi' is not installed."
    exit 1
fi

if ! command -v ghostty &> /dev/null; then
    echo "Error: 'ghostty' is not installed."
    exit 1
fi

# 2. Install xdg-desktop-portal-termfilechooser if not present
if ! pacman -Q xdg-desktop-portal-termfilechooser-git &> /dev/null && ! pacman -Q xdg-desktop-portal-termfilechooser &> /dev/null; then
    echo "Installing xdg-desktop-portal-termfilechooser..."
    if command -v yay &> /dev/null; then
        yay -S --noconfirm xdg-desktop-portal-termfilechooser-git
    elif command -v paru &> /dev/null; then
        paru -S --noconfirm xdg-desktop-portal-termfilechooser-git
    else
        echo "Error: No AUR helper (yay/paru) found. Please install 'xdg-desktop-portal-termfilechooser-git' manually."
        exit 1
    fi
else
    echo "✔ xdg-desktop-portal-termfilechooser is already installed."
fi

# 3. Create Configuration Directory
CONFIG_DIR="$HOME/.config/xdg-desktop-portal-termfilechooser"
mkdir -p "$CONFIG_DIR"

# 4. Create the Wrapper Script
# We use 'sh -c' to ensure Ghostty parses the arguments correctly and keeps the window context.
WRAPPER_PATH="$CONFIG_DIR/yazi-wrapper.sh"
echo "Creating wrapper script at $WRAPPER_PATH..."

cat > "$WRAPPER_PATH" << 'EOF'
#!/bin/sh
# Wrapper for yazi to work with xdg-desktop-portal-termfilechooser
# Generated by setup script

# Arguments provided by the portal:
# $1: multiple (0/1)
# $2: directory (0/1)
# $3: save (0/1)
# $4: path (recommended path)
# $5: out (file to write results to)

out="$5"

# Use full paths to avoid ambiguity
YAZI_BIN="$(which yazi)"
GHOSTTY_BIN="$(which ghostty)"

# Launch Ghostty with Yazi
# We use 'sh -c' to ensure argument parsing works correctly
# We use the class 'TUI.float.large' for custom large floating window rules
"$GHOSTTY_BIN" --class="TUI.float.large" -e sh -c "$YAZI_BIN --chooser-file='$out'"
EOF

chmod +x "$WRAPPER_PATH"

# 5. Configure termfilechooser to use the wrapper
echo "Configuring termfilechooser config..."
cat > "$CONFIG_DIR/config" << EOF
[filechooser]
cmd=$WRAPPER_PATH
EOF

# 6. Configure Hyprland Rules (for custom floating size)
HYPR_LOOKNFEEL="$HOME/.config/hypr/looknfeel.conf"
if [ -f "$HYPR_LOOKNFEEL" ]; then
    echo "Checking Hyprland rules in $HYPR_LOOKNFEEL..."
    if ! grep -q "TUI.float.large" "$HYPR_LOOKNFEEL"; then
        echo "Adding custom floating window rules for Yazi..."
        echo -e "\n# Yazi File Picker Rules (Added by setup script)" >> "$HYPR_LOOKNFEEL"
        echo "windowrulev2 = float, class:(TUI.float.large)" >> "$HYPR_LOOKNFEEL"
        echo "windowrulev2 = center, class:(TUI.float.large)" >> "$HYPR_LOOKNFEEL"
        echo "windowrulev2 = size 80% 80%, class:(TUI.float.large)" >> "$HYPR_LOOKNFEEL"
        echo "windowrulev2 = dimaround, class:(TUI.float.large)" >> "$HYPR_LOOKNFEEL"
        echo "windowrulev2 = stayfocused, class:(TUI.float.large)" >> "$HYPR_LOOKNFEEL"
    else
        echo "✔ Rules for 'TUI.float.large' already exist."
    fi
else
    echo "⚠ Warning: $HYPR_LOOKNFEEL not found. You may need to add window rules manually."
fi

# 7. Configure Portals (portals.conf)
PORTALS_CONF="$HOME/.config/xdg-desktop-portal/portals.conf"
mkdir -p "$(dirname "$PORTALS_CONF")"

echo "Updating $PORTALS_CONF..."

if [ -f "$PORTALS_CONF" ]; then
    # Backup existing config
    cp "$PORTALS_CONF" "${PORTALS_CONF}.bak"
    echo "Backed up existing portals.conf to ${PORTALS_CONF}.bak"
    
    # Check if FileChooser is already set
    if grep -q "org.freedesktop.impl.portal.FileChooser" "$PORTALS_CONF"; then
        # Replace existing line
        sed -i 's/^org.freedesktop.impl.portal.FileChooser=.*/org.freedesktop.impl.portal.FileChooser=termfilechooser/' "$PORTALS_CONF"
    else
        # Append to file
        # Ensure [preferred] exists, if not add it
        if ! grep -q "\[preferred\]" "$PORTALS_CONF"; then
            echo -e "\n[preferred]" >> "$PORTALS_CONF"
        fi
        echo "org.freedesktop.impl.portal.FileChooser=termfilechooser" >> "$PORTALS_CONF"
    fi
else
    # Create new file with Hyprland defaults
    cat > "$PORTALS_CONF" << EOF
[preferred]
default=hyprland;gtk
org.freedesktop.impl.portal.FileChooser=termfilechooser
EOF
fi

# 7. Restart Portals
echo "Restarting portal service..."
killall xdg-desktop-portal || true

echo "--- Setup Complete! ---"
echo "Try clicking 'Open Folder' in VS Code now."
