#!/usr/bin/env bash
set -euo pipefail

# Idempotent setup script for KMonad on Linux (Arch/pacman assumed)
# - Installs kmonad (if missing)
# - Ensures uinput permissions (udev rule + group)
# - Writes kmonad config (~/.config/kmonad/default.kbd)
# - Writes and enables systemd --user service
# - Optionally stops/disables keyd (conflicts with kmonad grabbing the keyboard)

KMONAD_DIR="${KMONAD_DIR:-$HOME/.config/kmonad}"
KMONAD_CFG="${KMONAD_CFG:-$KMONAD_DIR/default.kbd}"
KMONAD_SERVICE_DIR="$HOME/.config/systemd/user"
KMONAD_SERVICE="$KMONAD_SERVICE_DIR/kmonad.service"

KMONAD_WAYNERGY_CFG="$KMONAD_DIR/waynergy.kbd"
KMONAD_WAYNERGY_SERVICE="$KMONAD_SERVICE_DIR/kmonad-waynergy.service"

# Persisted keyboard path; override with --device
KBD_DEV_DEFAULT="/dev/input/by-path/platform-i8042-serio-0-event-kbd"
KBD_DEV="$KBD_DEV_DEFAULT"

DISABLE_KEYD=0
STOP_KEYD=1
FORCE_OVERWRITE=0
ENABLE_WAYNERGY=0

usage() {
  cat <<'USAGE'
Usage: setup_kmonad.sh [options]

Options:
  --device PATH        Input device path (default: platform-i8042...-event-kbd)
  --enable-waynergy    Install udev rule + kmonad-waynergy service (requires waynergy running with -b uinput)
  --disable-keyd       Disable and stop keyd permanently
  --keep-keyd          Do not stop keyd (kmonad will likely fail to start)
  --force              Overwrite existing kmonad config/service
  -h, --help           Show help

Notes:
- If this script adds you to new groups (input/uinput), you must logout/login
  (or reboot) for systemd --user services to see the new group membership.
USAGE
}

log() { printf "[kmonad-setup] %s\n" "$*"; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --device)
      KBD_DEV="${2:-}"; shift 2 ;;
    --enable-waynergy)
      ENABLE_WAYNERGY=1; shift ;;
    --disable-keyd)
      DISABLE_KEYD=1; shift ;;
    --keep-keyd)
      STOP_KEYD=0; shift ;;
    --force)
      FORCE_OVERWRITE=1; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      log "Unknown arg: $1"; usage; exit 2 ;;
  esac
done

if [[ -z "$KBD_DEV" ]]; then
  log "--device requires a PATH"; exit 2
fi

log "Using device: $KBD_DEV"

# 1) Install kmonad
if ! need_cmd kmonad; then
  if need_cmd pacman; then
    log "Installing kmonad via pacman (sudo required)..."
    sudo pacman -S --noconfirm kmonad
  else
    log "kmonad not found and pacman not available. Install kmonad manually."; exit 1
  fi
else
  log "kmonad already installed: $(kmonad --version 2>/dev/null || echo 'ok')"
fi

# 2) Kernel module
log "Ensuring uinput kernel module is loaded..."
sudo modprobe uinput || true

# 3) Groups + udev permissions
log "Ensuring uinput group exists..."
sudo groupadd --system uinput 2>/dev/null || true

needs_relogin=0
if ! id -nG "$USER" | tr ' ' '\n' | grep -qx input; then
  log "Adding $USER to group: input"
  sudo usermod -aG input "$USER"
  needs_relogin=1
fi
if ! id -nG "$USER" | tr ' ' '\n' | grep -qx uinput; then
  log "Adding $USER to group: uinput"
  sudo usermod -aG uinput "$USER"
  needs_relogin=1
fi

log "Installing udev rule for /dev/uinput permissions..."
UDEV_RULE_PATH="/etc/udev/rules.d/99-uinput.rules"
UDEV_RULE_CONTENT='KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"'

# Write rule only if missing or different
current_rule=""
if sudo test -f "$UDEV_RULE_PATH"; then
  current_rule=$(sudo cat "$UDEV_RULE_PATH" | tr -d '\r' || true)
fi
if [[ "$current_rule" != "$UDEV_RULE_CONTENT" ]]; then
  log "Writing $UDEV_RULE_PATH (sudo required)..."
  printf "%s\n" "$UDEV_RULE_CONTENT" | sudo tee "$UDEV_RULE_PATH" >/dev/null
  sudo udevadm control --reload-rules || true
  sudo systemctl restart systemd-udevd.service || true
  sudo udevadm trigger --name-match=/dev/uinput || true
fi

# Best-effort immediate fix for current node
if [[ -e /dev/uinput ]]; then
  sudo chgrp uinput /dev/uinput || true
  sudo chmod 0660 /dev/uinput || true
fi

# 4) Write config
log "Ensuring config exists at $KMONAD_CFG"
mkdir -p "$KMONAD_DIR"

if [[ -f "$KMONAD_CFG" && "$FORCE_OVERWRITE" -ne 1 ]]; then
  log "Config already exists; skipping (use --force to overwrite)."
else
  cat >"$KMONAD_CFG" <<CFG
;; Generated by setup_kmonad.sh
;; Equivalent behavior to keyd example:
;; - Caps: tap -> Esc, hold -> vim_nav layer
;; - Esc -> Caps
;; - vim_nav: h/j/k/l -> Ctrl+Left/Down/Up/Right

(defcfg
  input  (device-file "$KBD_DEV")
  output (uinput-sink "kmonad-virtual-keyboard")
  fallthrough true
)

(defsrc
  caps esc h j k l
)

(defalias
  capsnav (tap-hold-next 200 esc (layer-toggle vim_nav))
)

(deflayer base
  @capsnav caps h j k l
)

(deflayer vim_nav
  _ _ C-left C-down C-up C-rght
)
CFG
fi

log "Validating config syntax (dry-run)..."
kmonad -d "$KMONAD_CFG"

# 4b) Optional: Waynergy uinput keyboard support
if [[ "$ENABLE_WAYNERGY" -eq 1 ]]; then
  log "Enabling Waynergy support (udev + dedicated kmonad instance)..."
  log "NOTE: Waynergy must be started with: waynergy -b uinput"

  WAYNERGY_UDEV_RULE_PATH="/etc/udev/rules.d/99-waynergy-input.rules"
  WAYNERGY_UDEV_RULE_CONTENT='SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="waynergy keyboard", SYMLINK+="input/waynergy-kbd", MODE="0660", GROUP="input"'

  current_waynergy_rule=""
  if sudo test -f "$WAYNERGY_UDEV_RULE_PATH"; then
    current_waynergy_rule=$(sudo cat "$WAYNERGY_UDEV_RULE_PATH" | tr -d '\r' || true)
  fi

  if [[ "$current_waynergy_rule" != "$WAYNERGY_UDEV_RULE_CONTENT" ]]; then
    log "Writing $WAYNERGY_UDEV_RULE_PATH (sudo required)..."
    printf "%s\n" "$WAYNERGY_UDEV_RULE_CONTENT" | sudo tee "$WAYNERGY_UDEV_RULE_PATH" >/dev/null
    sudo udevadm control --reload-rules || true
    sudo udevadm trigger --subsystem-match=input || true
  fi

  log "Ensuring Waynergy kmonad config exists at $KMONAD_WAYNERGY_CFG"
  if [[ -f "$KMONAD_WAYNERGY_CFG" && "$FORCE_OVERWRITE" -ne 1 ]]; then
    log "Waynergy config already exists; skipping (use --force to overwrite)."
  else
    cat >"$KMONAD_WAYNERGY_CFG" <<'CFG'
;; KMonad config for Waynergy uinput keyboard
;; Expects a udev-created stable symlink: /dev/input/waynergy-kbd

(defcfg
  input  (device-file "/dev/input/waynergy-kbd")
  output (uinput-sink "kmonad-waynergy-virtual-keyboard")
  fallthrough true
)

(defsrc
  caps esc a s h j k l
)

(defalias
  capsnav (tap-hold-next 200 esc (layer-toggle vim_nav))
  a_ctl   (tap-hold-next-release 220 a lctl)
  s_sup   (tap-hold-next-release 220 s lmet)
)

(deflayer base
  @capsnav caps @a_ctl @s_sup h j k l
)

(deflayer vim_nav
  _ _ _ _ C-left C-down C-up C-rght
)
CFG
  fi

  log "Validating Waynergy config syntax (dry-run)..."
  kmonad -d "$KMONAD_WAYNERGY_CFG"

  log "Installing systemd user service: $KMONAD_WAYNERGY_SERVICE"
  if [[ -f "$KMONAD_WAYNERGY_SERVICE" && "$FORCE_OVERWRITE" -ne 1 ]]; then
    log "Waynergy service already exists; skipping (use --force to overwrite)."
  else
    cat >"$KMONAD_WAYNERGY_SERVICE" <<SERVICE
[Unit]
Description=KMonad remapping for Waynergy uinput keyboard
Requires=waynergy.service
After=waynergy.service

[Service]
Type=simple
ExecStart=/usr/bin/kmonad $KMONAD_WAYNERGY_CFG --log-level info
Restart=on-failure
RestartSec=1

[Install]
WantedBy=default.target
SERVICE
  fi
fi

# 5) systemd user service
log "Installing systemd user service: $KMONAD_SERVICE"
mkdir -p "$KMONAD_SERVICE_DIR"

if [[ -f "$KMONAD_SERVICE" && "$FORCE_OVERWRITE" -ne 1 ]]; then
  log "Service already exists; skipping (use --force to overwrite)."
else
  cat >"$KMONAD_SERVICE" <<SERVICE
[Unit]
Description=KMonad keyboard remapping

[Service]
Type=simple
ExecStart=/usr/bin/kmonad $KMONAD_CFG --log-level info
Restart=on-failure
RestartSec=1

[Install]
WantedBy=default.target
SERVICE
fi

systemctl --user daemon-reload

# 6) Handle keyd conflict
if systemctl list-unit-files --type=service 2>/dev/null | grep -q '^keyd\.service'; then
  if [[ "$DISABLE_KEYD" -eq 1 ]]; then
    log "Disabling and stopping keyd (sudo required)..."
    sudo systemctl disable --now keyd || true
  elif [[ "$STOP_KEYD" -eq 1 ]]; then
    if sudo systemctl is-active --quiet keyd; then
      log "Stopping keyd to avoid grab conflict (sudo required)..."
      sudo systemctl stop keyd || true
    fi
  fi
fi

# 7) Enable/start kmonad user service
log "Enabling and starting kmonad user service..."
systemctl --user enable --now kmonad.service || true

if [[ "$ENABLE_WAYNERGY" -eq 1 ]]; then
  log "Enabling and starting kmonad-waynergy user service..."
  systemctl --user enable --now kmonad-waynergy.service || true
fi

log "Status (last 30 lines):"
systemctl --user status kmonad --no-pager | tail -n 30 || true

if [[ "$needs_relogin" -eq 1 ]]; then
  log "IMPORTANT: You were added to new groups. Logout/login (or reboot), then run:"
  log "  systemctl --user restart kmonad.service"
fi

log "Done. If kmonad still fails, check: journalctl --user -u kmonad -n 100 --no-pager"
